In [1]:
import pandas as pd
import yfinance as yf
from sqlalchemy import create_engine

In [2]:
TM = yf.Ticker("TM")

In [3]:
financials = TM.financials
financials

,2022-03-31,2021-03-31,2020-03-31,2019-03-31
Research Development,None,None,None,None
Effect Of Accounting Charges,None,None,None,None
Income Before Tax,3990532000000.0,2932355000000.0,2792942000000.0,2645531000000.0
Minority Interest,908851000000.0,883782000000.0,720124000000.0,718985000000.0
Net Income,2850110000000.0,2245261000000.0,2036140000000.0,1882873000000.0
Selling General Administrative,2975977000000.0,2634625000000.0,2981965000000.0,2986695000000.0
Gross Profit,5971673000000.0,4832373000000.0,5381196000000.0,5443896000000.0
Ebit,2995696000000.0,2197748000000.0,2399231000000.0,2457201000000.0
Operating Income,2995696000000.0,2197748000000.0,2399231000000.0,2457201000000.0
Other Operating Expenses,None,None,None,None
Interest Expense,-32458000000.0,-42421000000.0,-44114000000.0,-28078000000.0
Extraordinary Items,None,None,None,None
Non Recurring,None,None,None,None
Other Items,None,None,None,None
Income Tax Expense,1115918000000.0,649976000000.0,681817000000.0,659944000000.0
Total Revenue,31379507000000.0,27214593000000.0,29866547000000.0,30225681000000.0
Total Operating Expenses,28383811000000.0,25016845000000.0,27467316000000.0,27768480000000.0
Cost Of Revenue,25407834000000.0,22382220000000.0,24485351000000.0,24781785000000.0
Total Other Income Expense Net,994836000000.0,734607000000.0,393711000000.0,188330000000.0
Discontinued Operations,None,None,None,None
Net Income From Continuing Ops,2874614000000.0,2282379000000.0,2111125000000.0,1985587000000.0
Net Income Applicable To Common Shares,2850110000000.0,2245261000000.0,2036140000000.0,1868085000000.0

In [4]:
financials = financials.transpose()
financials

,Research Development,Effect Of Accounting Charges,Income Before Tax,Minority Interest,Net Income,Selling General Administrative,Gross Profit,Ebit,Operating Income,Other Operating Expenses,...,Non Recurring,Other Items,Income Tax Expense,Total Revenue,Total Operating Expenses,Cost Of Revenue,Total Other Income Expense Net,Discontinued Operations,Net Income From Continuing Ops,Net Income Applicable To Common Shares
,,,,,,,,,,,,,,,,,,,,,
2022-03-31,None,None,3990532000000.0,908851000000.0,2850110000000.0,2975977000000.0,5971673000000.0,2995696000000.0,2995696000000.0,None,...,None,None,1115918000000.0,31379507000000.0,28383811000000.0,25407834000000.0,994836000000.0,None,2874614000000.0,2850110000000.0
2021-03-31,None,None,2932355000000.0,883782000000.0,2245261000000.0,2634625000000.0,4832373000000.0,2197748000000.0,2197748000000.0,None,...,None,None,649976000000.0,27214593000000.0,25016845000000.0,22382220000000.0,734607000000.0,None,2282379000000.0,2245261000000.0
2020-03-31,None,None,2792942000000.0,720124000000.0,2036140000000.0,2981965000000.0,5381196000000.0,2399231000000.0,2399231000000.0,None,...,None,None,681817000000.0,29866547000000.0,27467316000000.0,24485351000000.0,393711000000.0,None,2111125000000.0,2036140000000.0
2019-03-31,None,None,2645531000000.0,718985000000.0,1882873000000.0,2986695000000.0,5443896000000.0,2457201000000.0,2457201000000.0,None,...,None,None,659944000000.0,30225681000000.0,27768480000000.0,24781785000000.0,188330000000.0,None,1985587000000.0,1868085000000.0

In [5]:
financials.columns = financials.columns.str.replace(' ', '_')
financials.index.names = ['Date']
financials.head(2)

,Research_Development,Effect_Of_Accounting_Charges,Income_Before_Tax,Minority_Interest,Net_Income,Selling_General_Administrative,Gross_Profit,Ebit,Operating_Income,Other_Operating_Expenses,...,Non_Recurring,Other_Items,Income_Tax_Expense,Total_Revenue,Total_Operating_Expenses,Cost_Of_Revenue,Total_Other_Income_Expense_Net,Discontinued_Operations,Net_Income_From_Continuing_Ops,Net_Income_Applicable_To_Common_Shares
Date,,,,,,,,,,,,,,,,,,,,,
2022-03-31,None,None,3990532000000.0,908851000000.0,2850110000000.0,2975977000000.0,5971673000000.0,2995696000000.0,2995696000000.0,None,...,None,None,1115918000000.0,31379507000000.0,28383811000000.0,25407834000000.0,994836000000.0,None,2874614000000.0,2850110000000.0
2021-03-31,None,None,2932355000000.0,883782000000.0,2245261000000.0,2634625000000.0,4832373000000.0,2197748000000.0,2197748000000.0,None,...,None,None,649976000000.0,27214593000000.0,25016845000000.0,22382220000000.0,734607000000.0,None,2282379000000.0,2245261000000.0

In [7]:
engine = create_engine("mysql+pymysql://root:8669627426@localhost/toyotamotors")
financials.to_sql("financials", con = engine)

In [8]:
balance_sheet = TM.balance_sheet
balance_sheet

,2022-03-31,2021-03-31,2020-03-31,2019-03-31
Intangible Assets,5.282040e+11,4.774580e+11,3.747840e+11,NaN
Capital Surplus,4.985750e+11,4.972750e+11,4.893340e+11,4.871620e+11
Total Liab,4.053395e+13,3.797881e+13,3.263335e+13,3.186981e+13
Total Stockholder Equity,2.624597e+13,2.340455e+13,2.061889e+13,1.934815e+13
Minority Interest,9.088510e+11,8.837820e+11,7.201240e+11,7.189850e+11
Deferred Long Term Liab,6.637620e+11,6.311760e+11,6.254730e+11,NaN
Other Current Liab,5.746939e+12,4.719716e+12,4.532603e+12,4.479344e+12
Total Assets,6.768877e+13,6.226714e+13,5.397236e+13,5.193695e+13
Common Stock,3.970500e+11,3.970500e+11,3.970500e+11,3.970500e+11
Other Current Assets,3.229570e+12,4.922674e+12,2.717681e+12,1.425310e+11
Retained Earnings,2.645313e+13,2.410418e+13,2.223406e+13,2.198752e+13
Other Liab,3.038904e+12,2.824396e+12,2.696743e+12,2.887743e+12
Gains Losses Not Affecting Retained Earnings,-1.102782e+12,-1.593954e+12,-2.501557e+12,-3.523575e+12
Other Assets,1.090852e+13,1.036523e+13,9.047547e+12,1.182809e+12
Cash,4.299522e+12,3.274150e+12,2.682430e+12,2.790212e+12
Total Current Liabilities,2.184216e+13,2.146047e+13,1.814221e+13,1.822694e+13
Deferred Long Term Asset Charges,3.422020e+11,3.362240e+11,3.263640e+11,5.018720e+11
Short Long Term Debt,8.792600e+10,8.968100e+10,4.644708e+12,1.560380e+11
Other Stockholder Equity,2.203255e+12,1.307726e+12,5.855490e+11,-9.166500e+11
Property Plant Equipment,7.750427e+12,7.195309e+12,6.565514e+12,6.178503e+12
Total Current Assets,2.372229e+13,2.277680e+13,1.896332e+13,1.887924e+13
Long Term Investments,5.171578e+12,4.396826e+12,4.297564e+12,1.090829e+13
Net Tangible Assets,2.571776e+13,2.292709e+13,2.024410e+13,1.934815e+13
Net Receivables,3.306757e+12,3.071200e+12,2.885969e+12,2.940890e+12
Long Term Debt,1.752046e+12,1.629015e+12,1.151190e+13,7.655860e+11
Inventory,3.821356e+12,2.888028e+12,2.533892e+12,2.656396e+12
Accounts Payable,3.168084e+12,2.953716e+12,2.354425e+12,2.645984e+12
Short Term Investments,NaN,NaN,NaN,2.234892e+12